// <auto-generated />
namespace Vidiling.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class applyannotation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(applyannotation));
        
        string IMigrationMetadata.Id
        {
            get { return "201912022146001_applyannotation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
