// <auto-generated />
namespace Vidiling.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addMovieINdb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addMovieINdb));
        
        string IMigrationMetadata.Id
        {
            get { return "201912022343166_addMovieINdb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
